server:
  port: 9020

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: "${MONGO_DB_URI:mongodb://localhost:27017/whatsapp_messages}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://auth-server:8090}
  rabbitmq:
    host: rabbitmq
    port: 5672


app:
  firebase:
    service-account-file: "firebase/service-account-key.json"


eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eurekaserver:8070/eureka}
  instance:
    hostname: notification-service

#Eureka dashboard
info:
  app:
    name: "message-service"
    description: "Message service app (Development Profile)"
    version: "1.0.0-DEV"


#Actuator
management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
    metrics:
      access: read_only
    prometheus:
      access: read_only
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


logging:
  level:
    root: INFO
    tracz:
      notificationservice: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

#OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
