feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  common-service:
    url: ${COMMON_SERVICE_URL:http://common-service:8083}
