spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8060/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

# for Eureka dashboard
info:
  app:
    name: "gatewayserver"
    description: "Gateway server app"
    version: "1.0.0"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.webflux.handler: DEBUG
    org.springframework.web.reactive.DispatcherHandler: DEBUG

