spring:
  application:
    name: gateway-sever
  config:
    import: "optional:configserver:http://localhost:8060/"


#Acuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

# for Eureka dashboard
info:
  app:
    name: "gatewayserver"
    description: "Gateway server app"
    version: "1.0.0"

logging:
  level:
    org.springframework.security: debug

