server:
  port: 8090

spring:
  application:
    name: auth-server
  config:
    import: "optional:configserver:http://localhost:8060/"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

resilience4j.circuitbreaker:
  instances:
    userServiceProvision:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 5000
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true

#Actuator
management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
    metrics:
      access: read_only
    prometheus:
      access: read_only
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

# for Eureka dashboard
info:
  app:
    name: "auth-server"
    description: "Auth server app"
    version: "1.0.0"

logging:
  level:
    tracz:
      authserver: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

