apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-service-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-db
  labels:
    app: message-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service-db
  template:
    metadata:
      labels:
        app: message-service-db
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_DB_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_DB_PASSWORD
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MESSAGE_SERVICE_DB_NAME
        volumeMounts:
        - name: message-service-db-storage
          mountPath: /data/db
        readinessProbe:
          exec:
            command: ["mongo", "--eval", "db.adminCommand('ping')"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: message-service-db-storage
        persistentVolumeClaim:
          claimName: message-service-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: message-service-db
spec:
  selector:
    app: message-service-db
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  labels:
    app: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: gcr.io/${PROJECT_ID}/message-service:${TAG}
        ports:
        - containerPort: 9010
        env:
        - name: SPRING_APPLICATION_NAME
          value: "message-service"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://configserver:8060/"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eurekaserver:8070/eureka/"
        - name: MONGO_DB_URI
          value: "mongodb://$(MONGO_DB_USER):$(MONGO_DB_PASSWORD)@message-service-db:27017/$(MESSAGE_SERVICE_DB_NAME)?authSource=admin"
        - name: MONGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_DB_USER
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_DB_PASSWORD
        - name: MESSAGE_SERVICE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MESSAGE_SERVICE_DB_NAME
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_PASSWORD
        - name: OTEL_SERVICE_NAME
          value: "message-service"
        resources:
          limits:
            memory: "700Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9010
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9010
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message-service
  ports:
  - port: 9010
    targetPort: 9010
  type: ClusterIP