apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  AUTH_SERVER_DB_NAME: "${AUTH_SERVER_DB_NAME}"
  USER_SERVICE_DB_NAME: "${USER_SERVICE_DB_NAME}"
  MESSAGE_SERVICE_DB_NAME: "${MESSAGE_SERVICE_DB_NAME}"

  # MongoDB credentials
  MONGO_DB_USER: "${MONGO_DB_USER}"
  MONGO_DB_PASSWORD: "${MONGO_DB_PASSWORD}"

  # RabbitMQ credentials
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"

  # JWT Secret
  JWT_SECRET: "${JWT_SECRET}"

  # Other secrets
  ISSUER_URI: "${ISSUER_URI}"

  # Auth server secrets
  AUTH_SERVER_INTERNAL_SECRET: ${AUTH_SERVER_INTERNAL_SECRET}
  USER_SERVICE_CLIENT_SECRET: ${USER_SERVICE_CLIENT_SECRET}
  MESSAGE_SERVICE_CLIENT_SECRET: ${MESSAGE_SERVICE_CLIENT_SECRET}
  NOTIFICATION_SERVICE_CLIENT_SECRET: ${NOTIFICATION_SERVICE_CLIENT_SECRET}
  KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}

  # OAuth2 secrets
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
