services:

  microservice-db-postgres-config:
    image: postgres:17-alpine
    networks:
      - szopnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 3s
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  microservice-eureka-config:
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8060/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - szopnet
    deploy:
      resources:
        limits:
          memory: 700m