services:
  auth-server-db:
    container_name: auth-server-db
    environment:
      POSTGRES_DB: ${AUTH_SERVER_DB_NAME}
    ports:
      - "5432:5432"
    extends:
      file: common-config.yml
      service: microservice-db-config

  user-service-db:
    container_name: user-service-db
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB_NAME}
    ports:
      - "5433:5432"
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "szopszop/configserver"
    container_name: configserver
    ports:
      - "8060:8060"
    healthcheck:
      test: "curl --fail --silent localhost:8060/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: microservice-base-config
      
  eurekaserver:
    image: "szopszop/eurekaserver"
    container_name: eurekaserver
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  auth-server:
    image: "szopszop/auth-server"
    container_name: auth-server
    environment:
      SPRING_APPLICATION_NAME: auth-server
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-server-db:5432/${AUTH_SERVER_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      auth-server-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "9000:9000"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  user-service:
    image: "szopszop/user-service"
    container_name: user-service
    environment:
      SPRING_APPLICATION_NAME: user-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/${USER_SERVICE_DB_NAME}
    depends_on:
      user-service-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8080:8080"
    extends:
      file: common-config.yml
      service: microservice-eureka-config


networks:
  szopnet:
    driver: bridge
