spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/szopszop/whatsapp-clone-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info,httptrace,prometheus"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
server:
  port: 8060

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
  level:
    tracz:
      configserver: DEBUG