server:
  port: 8080

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://configserver:8060/"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true # dla localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

# for Eureka dashboard
info:
  app:
    name: "user-service"
    description: "User service app"
    version: "1.0.0"

logging:
  level:
    org.springframework.security: debug

