server:
  port: 8080

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://configserver:8060/"
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,info,httptrace,prometheus"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true # dla localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

# for Eureka dashboard
info:
  app:
    name: "user-service"
    description: "User service app"
    version: "1.0.0"

logging:
  level:
    tracz:
      userservice: debug

