ALTER TABLE users ADD COLUMN profile_image_url VARCHAR(255);
ALTER TABLE users ADD COLUMN about TEXT;
ALTER TABLE users ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'OFFLINE';

CREATE INDEX idx_users_status ON users(status);